### ISSUE TITLE
Running vagrant up: 404 error

### ISSUE THREAD

**Issue by LindaJeanne** [evolvingweb/chef-deploy-drupal#42]
Greetings,

following the vagrant instructions, the URL from which it tries to download precice64 is out of date:

`default: Adding box 'precise64' (v0) for provider: virtualbox
    default: Downloading: http://dl.dropbox.com/u/1537815/precise64.box
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

The requested URL returned error: 404 Not Found`

**Comment by amirkdv** [comment]
Should be good now!

**Comment by dergachev** [comment]
:+1:
